// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRs3JsriujkwIp_jEOR4LABzeHmt64b5o',
    appId: '1:590034108585:web:3c2b7b767b75c49b2fa9b8',
    messagingSenderId: '590034108585',
    projectId: 'self-login-f9488',
    authDomain: 'self-login-f9488.firebaseapp.com',
    storageBucket: 'self-login-f9488.appspot.com',
    measurementId: 'G-0X88M19WPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcLWDlE4JEwZ4jkniZiAnBckqXBbP5-dQ',
    appId: '1:590034108585:android:8e2fbe5b2d703c892fa9b8',
    messagingSenderId: '590034108585',
    projectId: 'self-login-f9488',
    storageBucket: 'self-login-f9488.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNNWGCv3SH2toiGkX-8DoAkDNH_Cw-UGs',
    appId: '1:590034108585:ios:90cb5f4cdc198fd22fa9b8',
    messagingSenderId: '590034108585',
    projectId: 'self-login-f9488',
    storageBucket: 'self-login-f9488.appspot.com',
    androidClientId: '590034108585-53h9673ker64fo2v2tr2f4cua0eo26pn.apps.googleusercontent.com',
    iosClientId: '590034108585-phrr06cpf5m88s1k0fp62vek9181rb4e.apps.googleusercontent.com',
    iosBundleId: 'com.example.selfLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNNWGCv3SH2toiGkX-8DoAkDNH_Cw-UGs',
    appId: '1:590034108585:ios:90cb5f4cdc198fd22fa9b8',
    messagingSenderId: '590034108585',
    projectId: 'self-login-f9488',
    storageBucket: 'self-login-f9488.appspot.com',
    androidClientId: '590034108585-53h9673ker64fo2v2tr2f4cua0eo26pn.apps.googleusercontent.com',
    iosClientId: '590034108585-phrr06cpf5m88s1k0fp62vek9181rb4e.apps.googleusercontent.com',
    iosBundleId: 'com.example.selfLogin',
  );
}
